version: '3.6'

services:
  menu:
    build: '.'
    depends_on:
      - 'database'
    ports:
      - '8000:3005'
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: restaurant_menu
      POSTGRES_HOST: 18.206.88.98
      POSTGRES_PORT: 5432